#!/usr/bin/env python3
"""Generate and validate machine-readable API spec from include/argparse-c.h."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER_PATH = ROOT / "include" / "argparse-c.h"
SPEC_PATH = ROOT / "docs" / "api-spec.json"
SPEC_SCHEMA_PATH = ROOT / "docs" / "api-spec.schema.json"
DOCS_EN_PATH = ROOT / "docs" / "api-spec.en.md"
DOCS_JA_PATH = ROOT / "docs" / "api-spec.ja.md"

AUTOGEN_COMMENT = (
    "<!-- Generated by scripts/sync_api_spec.py from include/argparse-c.h. Do not edit manually. -->\n"
)


@dataclass(frozen=True)
class Parameter:
    name: str
    type: str


@dataclass(frozen=True)
class Function:
    name: str
    return_type: str
    parameters: list[Parameter]


def normalize_spaces(text: str) -> str:
    return " ".join(text.replace("\n", " ").split())


def parse_parameters(raw: str) -> list[Parameter]:
    cleaned = normalize_spaces(raw)
    if cleaned == "void" or cleaned == "":
        return []

    params: list[Parameter] = []
    for chunk in [p.strip() for p in cleaned.split(",") if p.strip()]:
        if chunk == "void":
            continue
        if " " not in chunk:
            params.append(Parameter(name="", type=chunk))
            continue
        m = re.match(r"(?P<type>.+?)(?P<name>[A-Za-z_][A-Za-z0-9_]*)$", chunk)
        if not m:
            params.append(Parameter(name="", type=chunk))
            continue
        p_type = m.group("type").strip()
        name = m.group("name").strip()
        if not p_type:
            params.append(Parameter(name="", type=chunk))
            continue
        params.append(Parameter(name=name, type=p_type))
    return params


def parse_header_functions(header_text: str) -> list[Function]:
    pattern = re.compile(
        r"(?P<ret>[A-Za-z_][A-Za-z0-9_\s\*]*?)\s*(?P<name>ap_[A-Za-z0-9_]+)\s*\((?P<params>[^;]*?)\)\s*;",
        re.MULTILINE | re.DOTALL,
    )

    functions: list[Function] = []
    for match in pattern.finditer(header_text):
        name = match.group("name")
        ret = normalize_spaces(match.group("ret"))
        if ret.startswith("typedef"):
            continue
        params = parse_parameters(match.group("params"))
        functions.append(Function(name=name, return_type=ret, parameters=params))
    return functions


def classify_ownership(function: Function) -> dict[str, str | bool | None]:
    name = function.name
    if name in {"ap_parser_new", "ap_parser_new_with_options"}:
        return {
            "returns_owned_memory": True,
            "caller_must_free_with": "ap_parser_free",
            "notes_en": "Returns a new parser instance. Caller owns it.",
            "notes_ja": "新しい parser を返します。所有権は呼び出し側です。",
        }
    if name == "ap_add_subcommand":
        return {
            "returns_owned_memory": False,
            "caller_must_free_with": None,
            "notes_en": "Returned parser pointer is owned by the parent parser tree.",
            "notes_ja": "返される parser ポインタの所有権は親 parser ツリー側にあります。",
        }
    if function.return_type == "char *":
        return {
            "returns_owned_memory": True,
            "caller_must_free_with": "free",
            "notes_en": "Returned string is heap-allocated.",
            "notes_ja": "返される文字列はヒープ確保です。",
        }
    if name in {"ap_parse_args", "ap_parse_known_args"}:
        return {
            "returns_owned_memory": False,
            "caller_must_free_with": None,
            "notes_en": "On success, out_ns must be released with ap_namespace_free. parse_known_args also requires ap_free_tokens for unknown args.",
            "notes_ja": "成功時は out_ns を ap_namespace_free で解放します。parse_known_args では unknown 配列を ap_free_tokens で解放します。",
        }
    if name == "ap_completion_result_add":
        return {
            "returns_owned_memory": False,
            "caller_must_free_with": None,
            "notes_en": "Candidate memory is managed by ap_completion_result_free.",
            "notes_ja": "候補メモリは ap_completion_result_free で管理されます。",
        }
    if name in {"ap_completion_result_init", "ap_completion_result_free", "ap_namespace_free", "ap_parser_free", "ap_free_tokens"}:
        return {
            "returns_owned_memory": False,
            "caller_must_free_with": None,
            "notes_en": "Lifecycle helper; see function naming for ownership release semantics.",
            "notes_ja": "ライフサイクル補助 API です。解放責務は関数名の規約に従います。",
        }
    return {
        "returns_owned_memory": False,
        "caller_must_free_with": None,
        "notes_en": "No new ownership transfer in return value.",
        "notes_ja": "戻り値で新規所有権の移譲はありません。",
    }


def classify_error_contract(function: Function) -> dict[str, str | bool]:
    has_error_out = any(p.type.strip() == "ap_error *" for p in function.parameters)
    ret = function.return_type.strip()
    if ret == "int":
        return {
            "has_error_out": has_error_out,
            "success_return": "0",
            "failure_return": "-1",
            "notes_en": "Integer APIs follow 0 on success / -1 on failure.",
            "notes_ja": "int 戻り値 API は成功 0 / 失敗 -1 を返します。",
        }
    if ret == "bool":
        return {
            "has_error_out": has_error_out,
            "success_return": "true",
            "failure_return": "false",
            "notes_en": "Boolean APIs signal presence/success by true and miss/failure by false.",
            "notes_ja": "bool 戻り値 API は true が成功/存在、false が失敗/未存在を表します。",
        }
    if ret.endswith("*"):
        return {
            "has_error_out": has_error_out,
            "success_return": "non-NULL",
            "failure_return": "NULL",
            "notes_en": "Pointer-returning APIs use NULL as failure sentinel.",
            "notes_ja": "ポインタ戻り値 API は NULL を失敗値として使います。",
        }
    return {
        "has_error_out": has_error_out,
        "success_return": "n/a",
        "failure_return": "n/a",
        "notes_en": "See return type specific semantics.",
        "notes_ja": "戻り値型ごとの意味に従います。",
    }


def to_spec(functions: list[Function]) -> dict:
    return {
        "$schema": "./api-spec.schema.json",
        "spec_version": "1.0.0",
        "source_header": "include/argparse-c.h",
        "function_count": len(functions),
        "functions": [
            {
                "name": fn.name,
                "return_type": fn.return_type,
                "parameters": [
                    {"name": p.name, "type": p.type} for p in fn.parameters
                ],
                "ownership": classify_ownership(fn),
                "error_contract": classify_error_contract(fn),
            }
            for fn in functions
        ],
    }


def format_params_en(params: list[dict[str, str]]) -> str:
    if not params:
        return "void"
    return ", ".join(f"{p['type']} {p['name']}".strip() for p in params)


def render_markdown(spec: dict, lang: str) -> str:
    is_ja = lang == "ja"
    title = "argparse-c API Machine-readable Spec" if not is_ja else "argparse-c API 機械可読仕様"
    intro = (
        "This document is generated from `include/argparse-c.h` via `scripts/sync_api_spec.py`."
        if not is_ja
        else "このドキュメントは `scripts/sync_api_spec.py` が `include/argparse-c.h` から生成します。"
    )
    hdr = [
        "| Function | Signature | Return/Error Contract | Ownership / free responsibility |",
        "| --- | --- | --- | --- |",
    ]
    lines = [AUTOGEN_COMMENT.rstrip(), f"# {title}", "", intro, "", *hdr]
    for fn in spec["functions"]:
        ec = fn["error_contract"]
        ow = fn["ownership"]
        sig = f"`{fn['return_type']} {fn['name']}({format_params_en(fn['parameters'])})`"
        if is_ja:
            contract = f"成功: `{ec['success_return']}` / 失敗: `{ec['failure_return']}`。{ec['notes_ja']}"
            ownership = (
                f"free: `{ow['caller_must_free_with']}`。" if ow["caller_must_free_with"] else "free 関数指定なし。"
            ) + ow["notes_ja"]
        else:
            contract = f"success: `{ec['success_return']}` / failure: `{ec['failure_return']}`. {ec['notes_en']}"
            ownership = (
                f"free with `{ow['caller_must_free_with']}`. " if ow["caller_must_free_with"] else "no dedicated free function in return value. "
            ) + ow["notes_en"]
        lines.append(f"| `{fn['name']}` | {sig} | {contract} | {ownership} |")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files differ.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    header_text = HEADER_PATH.read_text(encoding="utf-8")
    functions = parse_header_functions(header_text)
    spec = to_spec(functions)

    generated_files = {
        SPEC_PATH: json.dumps(spec, ensure_ascii=False, indent=2) + "\n",
        DOCS_EN_PATH: render_markdown(spec, "en"),
        DOCS_JA_PATH: render_markdown(spec, "ja"),
    }

    changed = False
    for path, content in generated_files.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != content:
            changed = True
            if not args.check:
                path.write_text(content, encoding="utf-8")
                print(f"updated: {path.relative_to(ROOT)}")
            else:
                print(f"out-of-sync: {path.relative_to(ROOT)}", file=sys.stderr)

    if args.check and changed:
        print("Run: python scripts/sync_api_spec.py", file=sys.stderr)
        return 1

    if not changed:
        print("api spec is up-to-date")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
