#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_REPO = ROOT / "docs" / "repository"
SAMPLE_DIR = ROOT / "sample"

README_TARGETS = {
    ROOT / "README.md": DOCS_REPO / "README.md",
    ROOT / "README.ja.md": DOCS_REPO / "README.ja.md",
}

SAMPLE_FILES = [
    "example1.c",
    "example_completion.c",
    "example_subcommands.c",
    "example_manpage.c",
    "example_introspection.c",
]

README_REPLACEMENTS = [
    ("(./README.ja.md)", "(README.ja.md)"),
    ("(./README.md)", "(README.md)"),
    ("(./sample/example1.c)", "(sample/example1.c.md)"),
    ("(./sample/example_completion.c)", "(sample/example_completion.c.md)"),
    ("(./sample/example_subcommands.c)", "(sample/example_subcommands.c.md)"),
    ("(./sample/example_manpage.c)", "(sample/example_manpage.c.md)"),
    ("(./sample/example_introspection.c)", "(sample/example_introspection.c.md)"),
    ("(./docs/en/index.md)", "(../en/index.md)"),
    ("(./docs/en/getting-started.md)", "(../en/getting-started.md)"),
    ("(./docs/en/guides/)", "(../en/guides/)"),
    ("(./docs/api-spec.en.md)", "(../api-spec.en.md)"),
    ("(./docs/ja/index.md)", "(../ja/index.md)"),
    ("(./docs/ja/getting-started.md)", "(../ja/getting-started.md)"),
    ("(./docs/ja/guides/)", "(../ja/guides/)"),
    ("(./docs/api-spec.ja.md)", "(../api-spec.ja.md)"),
    ("<https://yoshihideshirai.github.io/argparse-c/en/>", "[../en/](../en/)"),
    ("<https://yoshihideshirai.github.io/argparse-c/ja/>", "[../ja/](../ja/)"),
    (
        "<https://yoshihideshirai.github.io/argparse-c/en/getting-started/>",
        "[../en/getting-started/](../en/getting-started/)",
    ),
    (
        "<https://yoshihideshirai.github.io/argparse-c/ja/getting-started/>",
        "[../ja/getting-started/](../ja/getting-started/)",
    ),
    (
        "<https://yoshihideshirai.github.io/argparse-c/en/guides/completion-callbacks/>",
        "[../en/guides/completion-callbacks/](../en/guides/completion-callbacks/)",
    ),
    (
        "<https://yoshihideshirai.github.io/argparse-c/ja/guides/completion-callbacks/>",
        "[../ja/guides/completion-callbacks/](../ja/guides/completion-callbacks/)",
    ),
    (
        "<https://yoshihideshirai.github.io/argparse-c/api-spec.en/>",
        "[../api-spec.en/](../api-spec.en/)",
    ),
    (
        "<https://yoshihideshirai.github.io/argparse-c/api-spec.ja/>",
        "[../api-spec.ja/](../api-spec.ja/)",
    ),
    ("<https://yoshihideshirai.github.io/argparse-c/>", "[../](../)"),
    ("https://yoshihideshirai.github.io/argparse-c/en/", "../en/"),
    ("https://yoshihideshirai.github.io/argparse-c/ja/", "../ja/"),
    ("https://yoshihideshirai.github.io/argparse-c/", "../"),
]


def sync_readmes() -> None:
    DOCS_REPO.mkdir(parents=True, exist_ok=True)
    for src, dst in README_TARGETS.items():
        text = src.read_text(encoding="utf-8")
        for before, after in README_REPLACEMENTS:
            text = text.replace(before, after)
        header = "<!-- Generated by scripts/sync_repository_docs.py. Do not edit manually. -->\n\n"
        dst.write_text(header + text, encoding="utf-8")


def sample_markdown(name: str, source: str) -> str:
    return (
        "<!-- Generated by scripts/sync_repository_docs.py. Do not edit manually. -->\n\n"
        f"# `sample/{name}`\n\n"
        "```c\n"
        f"{source}"
        "\n```\n"
    )


def sync_samples() -> None:
    target_dir = DOCS_REPO / "sample"
    target_dir.mkdir(parents=True, exist_ok=True)
    for name in SAMPLE_FILES:
        src = SAMPLE_DIR / name
        dst = target_dir / f"{name}.md"
        code = src.read_text(encoding="utf-8").rstrip("\n")
        dst.write_text(sample_markdown(name, code), encoding="utf-8")


def main() -> None:
    sync_readmes()
    sync_samples()


if __name__ == "__main__":
    main()
