#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_REPO = ROOT / "docs" / "repository"
SAMPLE_DIR = ROOT / "sample"

README_TARGETS = {
    ROOT / "README.md": DOCS_REPO / "README.md",
    ROOT / "README.ja.md": DOCS_REPO / "README.ja.md",
}

PAGES_BASE_URL = "https://yoshihideshirai.github.io/argparse-c"
README_MD_REPLACEMENTS = [
    ("(./README.ja.md)", "(README.ja.md)"),
    ("(./docs/repository/assets/argparse-c-demo.gif)", "(assets/argparse-c-demo.gif)"),
    ("(./sample/example1.c)", "(sample/example1.c.md)"),
    ("(./sample/example_completion.c)", "(sample/example_completion.c.md)"),
    ("(./sample/example_subcommands.c)", "(sample/example_subcommands.c.md)"),
    ("(./sample/example_manpage.c)", "(sample/example_manpage.c.md)"),
    ("(./sample/example_introspection.c)", "(sample/example_introspection.c.md)"),
    ("(./docs/en/index.md)", f"({PAGES_BASE_URL}/en/)"),
    ("(./docs/en/getting-started.md)", f"({PAGES_BASE_URL}/en/getting-started/)"),
    ("(./docs/en/guides/)", f"({PAGES_BASE_URL}/en/guides/)"),
    ("(./docs/api-spec.en.md)", f"({PAGES_BASE_URL}/api-spec.en/)"),
    ("(./docs/api-spec.json)", f"({PAGES_BASE_URL}/api-spec.json)"),
    ("(./docs/ja/index.md)", f"({PAGES_BASE_URL}/ja/)"),
    ("(./docs/ja/getting-started.md)", f"({PAGES_BASE_URL}/ja/getting-started/)"),
    ("(./docs/ja/guides/)", f"({PAGES_BASE_URL}/ja/guides/)"),
    ("(./docs/api-spec.ja.md)", f"({PAGES_BASE_URL}/api-spec.ja/)"),
    ("(./docs/api-spec.json)", f"({PAGES_BASE_URL}/api-spec.json)"),
    (f"<{PAGES_BASE_URL}/en/>", f"[{PAGES_BASE_URL}/en/]({PAGES_BASE_URL}/en/)"),
    (f"<{PAGES_BASE_URL}/ja/>", f"[{PAGES_BASE_URL}/ja/]({PAGES_BASE_URL}/ja/)"),
    (
        f"<{PAGES_BASE_URL}/en/getting-started/>",
        f"[{PAGES_BASE_URL}/en/getting-started/]({PAGES_BASE_URL}/en/getting-started/)",
    ),
    (
        f"<{PAGES_BASE_URL}/ja/getting-started/>",
        f"[{PAGES_BASE_URL}/ja/getting-started/]({PAGES_BASE_URL}/ja/getting-started/)",
    ),
    (
        f"<{PAGES_BASE_URL}/en/guides/completion-callbacks/>",
        f"[{PAGES_BASE_URL}/en/guides/completion-callbacks/]({PAGES_BASE_URL}/en/guides/completion-callbacks/)",
    ),
    (
        f"<{PAGES_BASE_URL}/ja/guides/completion-callbacks/>",
        f"[{PAGES_BASE_URL}/ja/guides/completion-callbacks/]({PAGES_BASE_URL}/ja/guides/completion-callbacks/)",
    ),
    (
        f"<{PAGES_BASE_URL}/api-spec.en/>",
        f"[{PAGES_BASE_URL}/api-spec.en/]({PAGES_BASE_URL}/api-spec.en/)",
    ),
    (
        f"<{PAGES_BASE_URL}/api-spec.ja/>",
        f"[{PAGES_BASE_URL}/api-spec.ja/]({PAGES_BASE_URL}/api-spec.ja/)",
    ),
    (f"<{PAGES_BASE_URL}/>", f"[{PAGES_BASE_URL}/]({PAGES_BASE_URL}/)"),
]

README_JA_MD_REPLACEMENTS = [
    ("(./README.md)", "(README.md)"),
    ("(./docs/repository/assets/argparse-c-demo.gif)", "(assets/argparse-c-demo.gif)"),
    ("(./docs/ja/index.md)", f"({PAGES_BASE_URL}/ja/)"),
    ("(./docs/ja/getting-started.md)", f"({PAGES_BASE_URL}/ja/getting-started/)"),
    ("(./docs/ja/guides/)", f"({PAGES_BASE_URL}/ja/guides/)"),
    ("(./docs/api-spec.ja.md)", f"({PAGES_BASE_URL}/api-spec.ja/)"),
    ("(./docs/api-spec.json)", f"({PAGES_BASE_URL}/api-spec.json)"),
    (f"<{PAGES_BASE_URL}/ja/>", f"[{PAGES_BASE_URL}/ja/]({PAGES_BASE_URL}/ja/)"),
]

README_REPLACEMENTS = {
    ROOT / "README.md": README_MD_REPLACEMENTS,
    ROOT / "README.ja.md": README_JA_MD_REPLACEMENTS,
}

AUTOGEN_HEADER = "<!-- Generated by scripts/sync_docs_repository.py. Do not edit manually. -->\n\n"

REPRODUCTION_COMMANDS = (
    "python scripts/sync_docs_repository.py",
    "git diff --exit-code -- docs/repository",
)


def sync_readmes() -> None:
    DOCS_REPO.mkdir(parents=True, exist_ok=True)
    for src, dst in README_TARGETS.items():
        text = src.read_text(encoding="utf-8")
        for before, after in README_REPLACEMENTS[src]:
            text = text.replace(before, after)
        dst.write_text(AUTOGEN_HEADER + text, encoding="utf-8")


def sample_markdown(name: str, source: str) -> str:
    return AUTOGEN_HEADER + f"# `sample/{name}`\n\n```c\n{source}\n```\n"


def sync_samples() -> None:
    target_dir = DOCS_REPO / "sample"
    target_dir.mkdir(parents=True, exist_ok=True)

    sample_files = sorted(SAMPLE_DIR.glob("*.c"))
    generated_names = set()

    for src in sample_files:
        name = src.name
        generated_names.add(f"{name}.md")
        dst = target_dir / f"{name}.md"
        code = src.read_text(encoding="utf-8").rstrip("\n")
        dst.write_text(sample_markdown(name, code), encoding="utf-8")

    for stale_doc in target_dir.glob("*.c.md"):
        if stale_doc.name not in generated_names:
            stale_doc.unlink()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Synchronize docs/repository snapshots with README and sample sources."
    )
    parser.add_argument(
        "--print-repro-cmds",
        action="store_true",
        help="Print reproduction commands for docs/repository synchronization checks.",
    )
    return parser.parse_args()


def print_reproduction_commands() -> None:
    print("docs/repository sync reproduction commands:")
    for command in REPRODUCTION_COMMANDS:
        print(command)


def main() -> None:
    args = parse_args()
    sync_readmes()
    sync_samples()

    if args.print_repro_cmds:
        print_reproduction_commands()


if __name__ == "__main__":
    main()
